CREATE TABLE IF NOT EXISTS Games (
    GameId INTEGER PRIMARY KEY AUTOINCREMENT,
    CurrentPlayer TEXT NOT NULL,
    BoardStateId INTEGER NOT NULL UNIQUE,
    GameMode INTEGER NOT NULL,
    Winner TEXT,
    GameStatus INTEGER NOT NULL,
    FOREIGN KEY (BoardStateId) REFERENCES BoardState(BoardId)
);
