CREATE TABLE IF NOT EXISTS GameMove (
    GameMoveId INTEGER PRIMARY KEY AUTOINCREMENT,
    GameId INTEGER NOT NULL,
    CellIndex INTEGER NOT NULL,
    Player TEXT NOT NULL,
    FOREIGN KEY (GameId) REFERENCES Game(GameId)
);

CREATE INDEX IF NOT EXISTS IX_GameMove_GameId ON GameMove(GameId);
