CREATE TABLE IF NOT EXISTS Scoreboards (
    GameId INTEGER PRIMARY KEY,
    XWins INTEGER NOT NULL DEFAULT 0,
    OWins INTEGER NOT NULL DEFAULT 0,
    Draws INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (GameId) REFERENCES Games(GameId)
);
