// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Api.DataAccess;

#nullable disable

namespace TicTacToe.Api.DataAccess.Migrations.EfMigrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    [Migration("20260822040505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TicTacToe.Api.Models.BoardState", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char?>("Cell1")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell2")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell3")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell4")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell5")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell6")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell7")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell8")
                        .HasColumnType("TEXT");

                    b.Property<char?>("Cell9")
                        .HasColumnType("TEXT");

                    b.HasKey("BoardId");

                    b.ToTable("BoardState");
                });

            modelBuilder.Entity("TicTacToe.Api.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardStateId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("CurrentPlayer")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameStatus")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("BoardStateId")
                        .IsUnique();

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TicTacToe.Api.Models.GameMove", b =>
                {
                    b.Property<int>("GameMoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Player")
                        .HasColumnType("TEXT");

                    b.HasKey("GameMoveId");

                    b.HasIndex("GameId");

                    b.ToTable("GameMove");
                });

            modelBuilder.Entity("TicTacToe.Api.Models.Scoreboard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draws")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("WinsO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("WinsX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Scoreboard", (string)null);
                });

            modelBuilder.Entity("TicTacToe.Api.Models.Game", b =>
                {
                    b.HasOne("TicTacToe.Api.Models.BoardState", "BoardState")
                        .WithOne()
                        .HasForeignKey("TicTacToe.Api.Models.Game", "BoardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardState");
                });

            modelBuilder.Entity("TicTacToe.Api.Models.GameMove", b =>
                {
                    b.HasOne("TicTacToe.Api.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TicTacToe.Api.Models.Game", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
